AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  CLASS_WEIGHTS: [0.7409680843135744, 1.168332641527453, 1.0544819925750062, 1.0762391587788254, 0.9599781228051405]
  DATASET: mydata
  IMG_DIRS: ['DEM']
  IMG_EXT: .tif
  INPUT_CHANNELS: 1
  LBL_DIR: y
  LBL_EXT: .tif
  NUM_CLASSES: 5
  ROOT: /path/to/data
  TEST_DIR: test
  TRAIN_DIR: train
  VALID_DIR: valid
DEBUG:
  DEBUG: False
  SAVE_BATCH_IMAGES_GT: False
  SAVE_BATCH_IMAGES_PRED: False
  SAVE_HEATMAPS_GT: False
  SAVE_HEATMAPS_PRED: False
EXPERIMENT_NAME: myexperiment
GPUS: (0, 1, 2, 3)
LOG_DIR: log
LOSS:
  BALANCE_WEIGHTS: [1]
  CLASS_BALANCE: False
  OHEMKEEP: 131072
  OHEMTHRES: 0.9
  USE_OHEM: True
MODEL:
  ALIGN_CORNERS: True
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      BLOCK: BOTTLENECK
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4]
      NUM_CHANNELS: [64]
      NUM_MODULES: 1
      NUM_RANCHES: 1
    STAGE2:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4]
      NUM_BRANCHES: 2
      NUM_CHANNELS: [48, 96]
      NUM_MODULES: 1
    STAGE3:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4, 4]
      NUM_BRANCHES: 3
      NUM_CHANNELS: [48, 96, 192]
      NUM_MODULES: 4
    STAGE4:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4, 4, 4]
      NUM_BRANCHES: 4
      NUM_CHANNELS: [48, 96, 192, 384]
      NUM_MODULES: 3
  NAME: hrnet
  PRETRAINED: ''
  NUM_OUTPUTS: 1
OUTPUT_DIR: output
PIN_MEMORY: True
PRINT_FREQ: 10
RANK: 0
TEST:
  BASE_SIZE: 256
  BATCH_SIZE_PER_GPU: 1
  IMAGE_SIZE: [256, 256]
  JUST_PREDICT: False
  MULTI_SCALE: False
  NUM_SAMPLES: 0
  OUTPUT_INDEX: -1
  SCALE_LIST: [1]
TRAIN:
  BASE_SIZE: 256
  BATCH_SIZE_PER_GPU: 96
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  EXTRA_EPOCH: 0
  EXTRA_LR: 0.001
  FREEZE_EPOCHS: -1
  FREEZE_LAYERS: 
  IGNORE_LABEL: -1
  IMAGE_SIZE: [128, 128]
  INIT_FN: xavier_normal_
  LR: 0.1
  LR_FACTOR: 0.1
  LR_STEP: [90, 110]
  MOMENTUM: 0.9
  MULTI_SCALE: False
  NESTEROV: False
  NONBACKBONE_KEYWORDS: []
  NONBACKBONE_MULT: 10
  NUM_SAMPLES: 0
  OPTIMIZER: SGD
  RESUME: True
  SCALE_FACTOR: 11
  SHUFFLE: True
  WD: 0.001
WORKERS: 4
